### ISSUE TITLE
Product variation images on products in WooCommerce are not getting the path updated

### ISSUE THREAD

**Issue by lukecav** [keycdn/cdn-enabler#45]
Example site URL.

https://rchsvt.org/product/rchs-baseball-caps/

Changing color, variation tries to load:

https://eadn-wc03-3359592.nxedge.io/wp-content/uploads/2021/07/RCHS-baseball-caps.jpg

The main image loads fine (which is the same coincidentally) :

https://eadn-wc03-3359592.nxedge.io/cdn/wp-content/uploads/2021/07/RCHS-baseball-caps.jpg

The main image loads fine because it is getting rewritten with `/cdn/` in the path. Variation images which I think are loaded from data attributes are not getting the `/cdn/` in the path and 404.

**Comment by lukecav** [comment]
The filter in the CDN Enabler plugin is already being used.

https://www.keycdn.com/support/wordpress-cdn-enabler-plugin#cdn_enabler_contents_after_rewrite

**Comment by coreykn** [comment]
It sounds like it is related the filter hook being used because if the hostname is rewritten that means CDN Enabler is working as expected. Did you check the page source against the regex pattern you're using in a regex tool, such as https://regex101.com? If yes, can you please provide the exact filter hook being used?

**Comment by jacksonwp** [comment]
In the meantime we switched CDNs so the example above now works properly as the new CDN doesn't have a subfolder path.

The URLs that were not getting filtered are in form.variations_form, stored in the data-product_variations attribute, where the URLs are escaped for JS, eg: 

`url&quot;:&quot;https:\/\/r9v5b5t4.stackpathcdn.com\/wp-content\/uploads\/2021\/07\/RCHS-baseball-caps.jpg`

**Comment by lukecav** [comment]
@coreykn This is being set in the CDN integration of the must-use plugin.

`/**
	 * Retrieve all filters for the integration.
	 *
	 * @return array[]
	 */
	protected function getFilters() {
		return [
			[ 'cdn_enabler_contents_after_rewrite', [ $this, 'filterCdnUrl' ], -100 ],
		];
	}

	/**
	 * Ensure that Nexcess CDN URIs always include the /cdn/ prefix.
	 *
	 * @param string $url The URL being filtered.
	 *
	 * @return string The potentially-modified $url.
	 */
	public function filterCdnUrl( $url ) {
		return (string) preg_replace( '#(\.nxedge\.io/)(?:cdn/)?([^\'",]+)#i', '$1cdn/$2', $url );
	}
}`

**Comment by coreykn** [comment]
Thanks. This is the same issue as https://wordpress.org/support/topic/using-the-new-filter-not-all-assets-have-the-cdn-path-being-added-back/. If the page source is ran through a regex tool you'll find that the pattern being using is causing this: https://regex101.com/r/AeNGyx/1

Is there a reason why `preg_replace()` is being used? I'd recommend using the `str_replace()` function instead. Otherwise you may end up essentially replicating the regex pattern CDN Enabler uses itself.
